"use strict"

module.exports = {
  url: "https://developer-diary.netlify.com",
  title: "Developer Diary",
  tagline: "Autodidact developer and sometimes hoop-jumper",
  copyright: "© 2019 willjw3, All rights reserved",
  author: {
    name: "WILL JAY",
    bio: "Self-taught web developer and whisky aficionado",
    contacts: {
      linkedin: "https://www.linkedin.com/in/will-ward-65234a170/",
      github: "https://github.com/willjw3",
      stackoverflow:
        "https://stackoverflow.com/users/10262432/will-ward?tab=profile",
      freecodecamp: "https://www.freecodecamp.org/willjw3",
      twitter: "https://twitter.com/willjw3",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 20,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 20,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
  ],
}
